### ISSUE TITLE
/server/main.js has no import of /imports/startup/server

### ISSUE THREAD

**Issue by Batistleman** [dburles/meteor-guide-starter-react#1]
The server entrypoint '/server/main.js' has no import of '/imports/startup/server' yet.

Shouldn't the following line be present in the file?

```
import '/imports/startup/client';
```

**Comment by dburles** [comment]
That's a good point considering `imports/startup/server/index.js` exists. I think the reason why I didn't was because it's an empty file. Edit: though routes.js is too so I have no excuse ;)

**Comment by dburles** [comment]
Thanks @Batistleman
